CREATE TABLE IF NOT EXISTS MealHistory ( 
 rid INT NOT NULL,
 uid INT NOT NULL,
 date DATETIME NOT NULL,
 type VARCHAR(255) NOT NULL,
 FOREIGN KEY(rid) REFERENCES recipe(rid),
 FOREIGN KEY(uid) REFERENCES user(uid),
 FOREIGN KEY(type) REFERENCES recipe(type),
 PRIMARY KEY(rid,uid)
 );
 